---
env: production
aws_region: us-east-1
cluster_name: opsforge-production
app_namespace: opsforge

prometheus_retention: 15d
prometheus_storage: 50Gi
grafana_ingress_enabled: true
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"

argocd_ingress_enabled: true
argocd_admin_password_bcrypt: "{{ lookup('env', 'ARGOCD_ADMIN_PASSWORD_BCRYPT') }}"
gitops_repo_url: "{{ lookup('env', 'GITOPS_REPO_URL') }}"
gitops_branch: main

slack_webhook_url: "{{ lookup('env', 'SLACK_WEBHOOK_URL') }}"
pagerduty_key: "{{ lookup('env', 'PAGERDUTY_KEY') }}"

alb_controller_role_arn: "{{ lookup('env', 'ALB_CONTROLLER_ROLE_ARN') }}"
cluster_autoscaler_role_arn: "{{ lookup('env', 'CLUSTER_AUTOSCALER_ROLE_ARN') }}"
